GET http://localhost:3210/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJNIHZpbm8gYSIsImVtYWlsIjoibWFpbEBnbWFpbC5jb20iLCJpYXQiOjE2NDE5MzgxMTcsImV4cCI6MTY0MTkzODEzN30.EvntYN-tii8FxiU6Pza98N3XHQ4OFwSjjSSuiDoIacE

###
GET http://localhost:3210/video-youtube

###
POST http://localhost:3210/users
Content-Type: application/json

{
    "name" : "vino arystio",
    "username" : "vinossss",
    "password" : "vinosana",
    "confpassword" : "vinosana"
}

###

###
PATCH  http://localhost:3210/video-youtube/1
Content-Type: application/json

{
    "nama" : "TWICE - Fanfare",

}


###
POST http://localhost:3210/login
Content-Type: application/json

{
    "email" : "vinosss@gmail.com",
    "password" : "sanavino"
}

###
GET http://localhost:3210/token


###
Delete http://localhost:3210/video-youtube/1



